# Generated by Django 3.1.2 on 2020-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmoloyeeInfo',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_firstname', models.CharField(max_length=255, unique=True)),
                ('emp_lastname', models.CharField(max_length=255)),
                ('emp_salary', models.FloatField()),
            ],
        ),
    ]
